### ISSUE TITLE
[Bug] v5.3.0: LaravelNovaUi is not defined

### ISSUE THREAD

**Issue by Jonathankli** [outl1ne/nova-settings#196] opened 2024-12-19 09:14 UTC
Hello,

I noticed after updating from 5.2.4 to 5.3.0 I will get a JS error, which causes braking nova and show a blank page.
Using Nova 4.35.5 and PHP 8.3.12.
![Bildschirmfoto 2024-12-19 um 10 10 45](https://github.com/user-attachments/assets/14811ccd-46d9-4037-8bcf-4f09213055e0)

```
nova-settings:2 Uncaught ReferenceError: LaravelNovaUi is not defined
    at 189 (nova-settings:2:7470)
    at r (nova-settings:2:11818)
    at nova-settings:2:12056
    at app.js:117:47
    at Array.forEach (<anonymous>)
    at br.boot (app.js:117:27)
    at br.liftOff (app.js:170:10)
    at main:51:14
```

Can you take a look?
Regards

**Comment by Tarpsvo** [comment] 2024-12-19 12:07
Umm, I can't reproduce nor find any trace of LaravelNovaUi in the code. Are you sure you didn't install 6.0.0 and revert back to 5.3.0 somehow?

**Comment by Tarpsvo** [comment] 2024-12-20 08:37
Oooof, I think I released the wrong branch for Nova v4. :( Fixed now, same release number.

**Closed by Tarpsvo** 2024-12-20 08:37 UTC
